/**
 * Contract tests derived from contracts/Reservation.ocl
 * (regenerated by solidsdd.derive.tests).
 *
 * W1: PrincipalAuthorized, QuantityPositive, SufficientAvailableStock (pre),
 *     HoldCreatedWithTtl, AvailableStockReduced.
 * W2: InsufficientStockError, NoHoldCreatedOnInsufficientStock,
 *     AvailableStockUnchangedOnInsufficientStock (failure-path posts).
 * W3: UnauthorizedErrorOnReserve / NoHoldCreatedOnUnauthorizedReserve /
 *     AvailableStockUnchangedOnUnauthorizedReserve;
 *     Reservation::release UnauthorizedErrorOnRelease /
 *     HoldsUnchangedOnUnauthorizedRelease /
 *     AvailableStockUnchangedOnUnauthorizedRelease.
 * W4: Reservation::release HoldExists (pre), AvailableStockRestored,
 *     HoldRemoved (authorized restore).
 * W5: Reservation::expire HoldExists, HoldPastTtl (pre);
 *     AvailableStockRestoredOnExpiry, HoldRemoved (success);
 *     PreconditionError + no stock/hold mutation when missing or not past TTL.
 *     HoldPastTtl is arranged by expiresAt already in the past (no sleeps);
 *     injectable service clock is an equivalent checkability path.
 * add-reservation-lookup W1: Reservation::lookup PrincipalAuthorized,
 *     HoldExists (pre); ResultIsHoldDetails, AvailableStockUnchanged,
 *     HoldsUnchanged (authorized get-by-id; no mutation).
 * add-reservation-lookup W2: HoldMissingOrNotVisibleErrorOnLookup /
 *     HoldsUnchangedOnHoldMissingLookup (PreconditionError; no mutation);
 *     UnauthorizedErrorOnLookup / HoldsUnchangedOnUnauthorizedLookup /
 *     AvailableStockUnchangedOnUnauthorizedLookup (UnauthorizedError; no mutation).
 * add-lookup-available-stock W2: ResultIsHoldDetails includes
 *     result.availableStock = ReservationService.availableStock(hold.sku)
 *     at lookup time (current stock, not a reserve-time snapshot);
 *     AvailableStockUnchanged / HoldsUnchanged / error channels retained.
 * add-concurrent-last-unit-safety W1: InsufficientStockError is the shared
 *     named channel for sequential insufficient stock and contract-testable
 *     race-loser paths (availableStock@pre < quantity); inv
 *     AvailableStockNonNegative and post AvailableStockNonNegativeAfterReserve
 *     keep operated-SKU stock >= 0 on success and insufficient-stock paths.
 *     Full concurrent interleaving exclusivity is deferred to W2 / formal.
 * add-list-holds W1: Reservation::list PrincipalAuthorized (pre);
 *     ResultIsFullDumpOfVisibleHolds (LookupResponse-equivalent items
 *     including availableStock; same visibility as get-by-id / holds());
 *     EmptyCollectionWhenNoneVisible; HoldsUnchanged /
 *     AvailableStockUnchanged (authorized read-only full dump);
 *     UnauthorizedErrorOnList / HoldsUnchangedOnUnauthorizedList /
 *     AvailableStockUnchangedOnUnauthorizedList (UnauthorizedError; no
 *     mutation). Aligns with OpenAPI GET /reservations bare array of
 *     LookupResponse (empty OK).
 */
import { afterEach, describe, expect, it } from "vitest";
import {
  type Hold,
  InsufficientStockError,
  PreconditionError,
  ReservationService,
  UnauthorizedError,
} from "../../src/reservation.js";

const AUTHORIZED = "principal-authorized";
const UNAUTHORIZED = "principal-denied";

/**
 * Arrange HoldPastTtl without wall-clock sleep: set expiresAt strictly before
 * the service clock. Prefer this (or injectable setNow) over sleeping until TTL.
 * Mutates the domain hold so expiresAt is already in the past at expire time.
 */
function arrangeHoldPastTtl(hold: Hold): void {
  const pastIso = new Date(Date.now() - 60_000).toISOString();
  const stored = ReservationService.holds().find((h) => h.holdId === hold.holdId);
  if (!stored) {
    throw new Error(`arrangeHoldPastTtl: hold not found: ${hold.holdId}`);
  }
  stored.expiresAt = pastIso;
  hold.expiresAt = pastIso;
}

describe("OCL Reservation::reserve", () => {
  afterEach(() => {
    ReservationService.reset();
  });

  it("pre PrincipalAuthorized: unauthorized principal is rejected", () => {
    ReservationService.seedStock("SKU-1", 10);
    expect(() =>
      ReservationService.reserve(UNAUTHORIZED, "SKU-1", 1, 300),
    ).toThrow(UnauthorizedError);
    expect(ReservationService.availableStock("SKU-1")).toBe(10);
    expect(ReservationService.holds()).toHaveLength(0);
  });

  it("pre QuantityPositive: quantity > 0 is enforced", () => {
    ReservationService.seedStock("SKU-1", 10);
    expect(() =>
      ReservationService.reserve(AUTHORIZED, "SKU-1", 0, 300),
    ).toThrow(PreconditionError);
    expect(ReservationService.availableStock("SKU-1")).toBe(10);
    expect(ReservationService.holds()).toHaveLength(0);
  });

  it("pre SufficientAvailableStock: availableStock(sku) >= quantity is enforced", () => {
    ReservationService.seedStock("SKU-1", 2);
    expect(() =>
      ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300),
    ).toThrow(InsufficientStockError);
  });

  it("post HoldCreatedWithTtl: hold created with sku, quantity, and expiresAt = now + ttlSeconds", () => {
    ReservationService.seedStock("SKU-1", 10);
    const before = Date.now();
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    const after = Date.now();

    expect(hold.sku).toBe("SKU-1");
    expect(hold.quantity).toBe(4);
    expect(hold.holdId.length).toBeGreaterThan(0);
    const expiresAtMs = Date.parse(hold.expiresAt);
    expect(expiresAtMs).toBeGreaterThanOrEqual(before + 300_000);
    expect(expiresAtMs).toBeLessThanOrEqual(after + 300_000);
    expect(ReservationService.holds()).toHaveLength(1);
  });

  it("post AvailableStockReduced: availableStock decreases by reserved quantity", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    expect(ReservationService.availableStock("SKU-1")).toBe(6);
    expect(hold.availableStock).toBe(6);
  });

  it("post InsufficientStockError: available < quantity yields named InsufficientStockError (not a language builtin)", () => {
    ReservationService.seedStock("SKU-1", 2);
    let caught: unknown;
    try {
      ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    } catch (e) {
      caught = e;
    }
    expect(caught).toBeInstanceOf(InsufficientStockError);
    expect(caught).not.toBeInstanceOf(PreconditionError);
    expect(caught).not.toBeInstanceOf(TypeError);
    expect(caught).not.toBeInstanceOf(RangeError);
    expect((caught as InsufficientStockError).errorType).toBe(
      "InsufficientStockError",
    );
    expect((caught as InsufficientStockError).name).toBe(
      "InsufficientStockError",
    );
  });

  it("post InsufficientStockError: zero available stock also yields InsufficientStockError", () => {
    ReservationService.seedStock("SKU-1", 0);
    expect(() =>
      ReservationService.reserve(AUTHORIZED, "SKU-1", 1, 300),
    ).toThrow(InsufficientStockError);
  });

  it("post NoHoldCreatedOnInsufficientStock: holds() equals holds()@pre when available < quantity", () => {
    ReservationService.seedStock("SKU-1", 10);
    const existing = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const holdsBefore = ReservationService.holds().map((h) => h.holdId);

    expect(() =>
      ReservationService.reserve(AUTHORIZED, "SKU-1", 8, 300),
    ).toThrow(InsufficientStockError);

    const holdsAfter = ReservationService.holds();
    expect(holdsAfter.map((h) => h.holdId)).toEqual(holdsBefore);
    expect(holdsAfter).toHaveLength(1);
    expect(holdsAfter[0]?.holdId).toBe(existing.holdId);
  });

  it("post NoHoldCreatedOnInsufficientStock: no hold when none existed before failure", () => {
    ReservationService.seedStock("SKU-1", 2);
    expect(() =>
      ReservationService.reserve(AUTHORIZED, "SKU-1", 5, 300),
    ).toThrow(InsufficientStockError);
    expect(ReservationService.holds()).toHaveLength(0);
  });

  it("post AvailableStockUnchangedOnInsufficientStock: availableStock equals availableStock@pre when available < quantity", () => {
    ReservationService.seedStock("SKU-1", 4);
    const stockBefore = ReservationService.availableStock("SKU-1");

    expect(() =>
      ReservationService.reserve(AUTHORIZED, "SKU-1", 7, 300),
    ).toThrow(InsufficientStockError);

    expect(ReservationService.availableStock("SKU-1")).toBe(stockBefore);
    expect(ReservationService.availableStock("SKU-1")).toBe(4);
  });

  it("post AvailableStockUnchangedOnInsufficientStock: partial prior hold does not alter remaining stock on failure", () => {
    ReservationService.seedStock("SKU-1", 10);
    ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const stockBefore = ReservationService.availableStock("SKU-1");
    expect(stockBefore).toBe(7);

    expect(() =>
      ReservationService.reserve(AUTHORIZED, "SKU-1", 8, 300),
    ).toThrow(InsufficientStockError);

    expect(ReservationService.availableStock("SKU-1")).toBe(stockBefore);
    expect(ReservationService.availableStock("SKU-1")).toBe(7);
  });

  it("post InsufficientStockError (race-loser contract path): after last unit is held, further reserve yields same named InsufficientStockError", () => {
    // Sequential stand-in for a concurrent race loser observing availableStock@pre < quantity
    // (W1 contract-testable path; full interleaving exclusivity is W2 / formal).
    ReservationService.seedStock("SKU-1", 1);
    const winner = ReservationService.reserve(AUTHORIZED, "SKU-1", 1, 300);
    expect(ReservationService.availableStock("SKU-1")).toBe(0);

    let caught: unknown;
    try {
      ReservationService.reserve(AUTHORIZED, "SKU-1", 1, 300);
    } catch (e) {
      caught = e;
    }
    expect(caught).toBeInstanceOf(InsufficientStockError);
    expect(caught).not.toBeInstanceOf(PreconditionError);
    expect(caught).not.toBeInstanceOf(TypeError);
    expect(caught).not.toBeInstanceOf(RangeError);
    expect((caught as InsufficientStockError).errorType).toBe(
      "InsufficientStockError",
    );
    expect((caught as InsufficientStockError).name).toBe(
      "InsufficientStockError",
    );
    expect(ReservationService.holds()).toHaveLength(1);
    expect(ReservationService.holds()[0]?.holdId).toBe(winner.holdId);
    expect(ReservationService.availableStock("SKU-1")).toBe(0);
  });

  it("inv AvailableStockNonNegative / post AvailableStockNonNegativeAfterReserve: stock stays >= 0 after successful reserve", () => {
    ReservationService.seedStock("SKU-1", 10);
    ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    expect(ReservationService.availableStock("SKU-1")).toBeGreaterThanOrEqual(0);
    expect(ReservationService.availableStock("SKU-1")).toBe(6);
  });

  it("inv AvailableStockNonNegative / post AvailableStockNonNegativeAfterReserve: stock stays >= 0 when reserve depletes to zero", () => {
    ReservationService.seedStock("SKU-1", 5);
    ReservationService.reserve(AUTHORIZED, "SKU-1", 5, 300);
    expect(ReservationService.availableStock("SKU-1")).toBeGreaterThanOrEqual(0);
    expect(ReservationService.availableStock("SKU-1")).toBe(0);
  });

  it("inv AvailableStockNonNegative / post AvailableStockNonNegativeAfterReserve: stock stays >= 0 after InsufficientStockError", () => {
    ReservationService.seedStock("SKU-1", 2);
    expect(() =>
      ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300),
    ).toThrow(InsufficientStockError);
    expect(ReservationService.availableStock("SKU-1")).toBeGreaterThanOrEqual(0);
    expect(ReservationService.availableStock("SKU-1")).toBe(2);
  });

  it("inv AvailableStockNonNegative / post AvailableStockNonNegativeAfterReserve: stock stays >= 0 on last-unit race-loser contract path", () => {
    ReservationService.seedStock("SKU-1", 1);
    ReservationService.reserve(AUTHORIZED, "SKU-1", 1, 300);
    expect(() =>
      ReservationService.reserve(AUTHORIZED, "SKU-1", 1, 300),
    ).toThrow(InsufficientStockError);
    expect(ReservationService.availableStock("SKU-1")).toBeGreaterThanOrEqual(0);
    expect(ReservationService.availableStock("SKU-1")).toBe(0);
  });

  it("post UnauthorizedErrorOnReserve: unauthorized yields named UnauthorizedError (not a language builtin)", () => {
    ReservationService.seedStock("SKU-1", 10);
    let caught: unknown;
    try {
      ReservationService.reserve(UNAUTHORIZED, "SKU-1", 2, 300);
    } catch (e) {
      caught = e;
    }
    expect(caught).toBeInstanceOf(UnauthorizedError);
    expect(caught).not.toBeInstanceOf(PreconditionError);
    expect(caught).not.toBeInstanceOf(InsufficientStockError);
    expect(caught).not.toBeInstanceOf(TypeError);
    expect((caught as UnauthorizedError).errorType).toBe("UnauthorizedError");
    expect((caught as UnauthorizedError).name).toBe("UnauthorizedError");
  });

  it("post NoHoldCreatedOnUnauthorizedReserve: holds() equals holds()@pre when unauthorized", () => {
    ReservationService.seedStock("SKU-1", 10);
    const existing = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const holdsBefore = ReservationService.holds().map((h) => h.holdId);

    expect(() =>
      ReservationService.reserve(UNAUTHORIZED, "SKU-1", 1, 300),
    ).toThrow(UnauthorizedError);

    const holdsAfter = ReservationService.holds();
    expect(holdsAfter.map((h) => h.holdId)).toEqual(holdsBefore);
    expect(holdsAfter).toHaveLength(1);
    expect(holdsAfter[0]?.holdId).toBe(existing.holdId);
  });

  it("post NoHoldCreatedOnUnauthorizedReserve: no hold when none existed before unauthorized failure", () => {
    ReservationService.seedStock("SKU-1", 10);
    expect(() =>
      ReservationService.reserve(UNAUTHORIZED, "SKU-1", 1, 300),
    ).toThrow(UnauthorizedError);
    expect(ReservationService.holds()).toHaveLength(0);
  });

  it("post AvailableStockUnchangedOnUnauthorizedReserve: availableStock equals availableStock@pre when unauthorized", () => {
    ReservationService.seedStock("SKU-1", 10);
    ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const stockBefore = ReservationService.availableStock("SKU-1");
    expect(stockBefore).toBe(7);

    expect(() =>
      ReservationService.reserve(UNAUTHORIZED, "SKU-1", 2, 300),
    ).toThrow(UnauthorizedError);

    expect(ReservationService.availableStock("SKU-1")).toBe(stockBefore);
    expect(ReservationService.availableStock("SKU-1")).toBe(7);
  });
});

describe("OCL Reservation::release", () => {
  afterEach(() => {
    ReservationService.reset();
  });

  it("pre PrincipalAuthorized: unauthorized principal is rejected", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);

    expect(() =>
      ReservationService.release(UNAUTHORIZED, hold.holdId),
    ).toThrow(UnauthorizedError);
  });

  it("pre HoldExists: missing holdId is rejected with named PreconditionError", () => {
    ReservationService.seedStock("SKU-1", 10);
    ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);

    let caught: unknown;
    try {
      ReservationService.release(AUTHORIZED, "hold-does-not-exist");
    } catch (e) {
      caught = e;
    }
    expect(caught).toBeInstanceOf(PreconditionError);
    expect(caught).not.toBeInstanceOf(UnauthorizedError);
    expect(caught).not.toBeInstanceOf(InsufficientStockError);
    expect(caught).not.toBeInstanceOf(TypeError);
    expect((caught as PreconditionError).errorType).toBe("PreconditionError");
    expect((caught as PreconditionError).name).toBe("PreconditionError");
  });

  it("pre HoldExists: missing hold leaves stock and holds unchanged", () => {
    ReservationService.seedStock("SKU-1", 10);
    const existing = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const stockBefore = ReservationService.availableStock("SKU-1");
    const holdsBefore = ReservationService.holds().map((h) => h.holdId);

    expect(() =>
      ReservationService.release(AUTHORIZED, "hold-does-not-exist"),
    ).toThrow(PreconditionError);

    expect(ReservationService.availableStock("SKU-1")).toBe(stockBefore);
    expect(ReservationService.holds().map((h) => h.holdId)).toEqual(
      holdsBefore,
    );
    expect(ReservationService.holds()[0]?.holdId).toBe(existing.holdId);
  });

  it("post UnauthorizedErrorOnRelease: unauthorized yields named UnauthorizedError (not a language builtin)", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    let caught: unknown;
    try {
      ReservationService.release(UNAUTHORIZED, hold.holdId);
    } catch (e) {
      caught = e;
    }
    expect(caught).toBeInstanceOf(UnauthorizedError);
    expect(caught).not.toBeInstanceOf(PreconditionError);
    expect(caught).not.toBeInstanceOf(InsufficientStockError);
    expect(caught).not.toBeInstanceOf(TypeError);
    expect((caught as UnauthorizedError).errorType).toBe("UnauthorizedError");
    expect((caught as UnauthorizedError).name).toBe("UnauthorizedError");
  });

  it("post HoldsUnchangedOnUnauthorizedRelease: holds() equals holds()@pre when unauthorized", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const holdsBefore = ReservationService.holds().map((h) => ({ ...h }));

    expect(() =>
      ReservationService.release(UNAUTHORIZED, hold.holdId),
    ).toThrow(UnauthorizedError);

    const holdsAfter = ReservationService.holds();
    expect(holdsAfter).toHaveLength(1);
    expect(holdsAfter[0]?.holdId).toBe(hold.holdId);
    expect(holdsAfter[0]?.sku).toBe(holdsBefore[0]?.sku);
    expect(holdsAfter[0]?.quantity).toBe(holdsBefore[0]?.quantity);
    expect(holdsAfter[0]?.expiresAt).toBe(holdsBefore[0]?.expiresAt);
  });

  it("post AvailableStockUnchangedOnUnauthorizedRelease: availableStock for hold sku equals @pre when unauthorized", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const stockBefore = ReservationService.availableStock("SKU-1");
    expect(stockBefore).toBe(7);

    expect(() =>
      ReservationService.release(UNAUTHORIZED, hold.holdId),
    ).toThrow(UnauthorizedError);

    expect(ReservationService.availableStock("SKU-1")).toBe(stockBefore);
    expect(ReservationService.availableStock("SKU-1")).toBe(7);
  });

  it("post AvailableStockRestored: authorized release restores held quantity to available stock", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    const stockBefore = ReservationService.availableStock("SKU-1");
    expect(stockBefore).toBe(6);

    ReservationService.release(AUTHORIZED, hold.holdId);

    expect(ReservationService.availableStock("SKU-1")).toBe(
      stockBefore + hold.quantity,
    );
    expect(ReservationService.availableStock("SKU-1")).toBe(10);
  });

  it("post HoldRemoved: authorized release removes the hold", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    expect(ReservationService.holds()).toHaveLength(1);

    ReservationService.release(AUTHORIZED, hold.holdId);

    expect(ReservationService.holds()).toHaveLength(0);
    expect(
      ReservationService.holds().find((h) => h.holdId === hold.holdId),
    ).toBeUndefined();
  });

  it("post AvailableStockRestored + HoldRemoved: other holds and their stock remain intact", () => {
    ReservationService.seedStock("SKU-1", 10);
    ReservationService.seedStock("SKU-2", 5);
    const hold1 = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const hold2 = ReservationService.reserve(AUTHORIZED, "SKU-2", 2, 300);
    expect(ReservationService.availableStock("SKU-1")).toBe(7);
    expect(ReservationService.availableStock("SKU-2")).toBe(3);

    ReservationService.release(AUTHORIZED, hold1.holdId);

    expect(ReservationService.availableStock("SKU-1")).toBe(10);
    expect(ReservationService.availableStock("SKU-2")).toBe(3);
    expect(ReservationService.holds()).toHaveLength(1);
    expect(ReservationService.holds()[0]?.holdId).toBe(hold2.holdId);
  });
});

describe("OCL Reservation::expire", () => {
  afterEach(() => {
    ReservationService.reset();
  });

  it("pre HoldExists: missing holdId is rejected with named PreconditionError", () => {
    ReservationService.seedStock("SKU-1", 10);
    ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);

    let caught: unknown;
    try {
      ReservationService.expire("hold-does-not-exist");
    } catch (e) {
      caught = e;
    }
    expect(caught).toBeInstanceOf(PreconditionError);
    expect(caught).not.toBeInstanceOf(UnauthorizedError);
    expect(caught).not.toBeInstanceOf(InsufficientStockError);
    expect(caught).not.toBeInstanceOf(TypeError);
    expect((caught as PreconditionError).errorType).toBe("PreconditionError");
    expect((caught as PreconditionError).name).toBe("PreconditionError");
  });

  it("post PreconditionErrorOnExpireHoldMissing: missing hold leaves stock and holds unchanged", () => {
    ReservationService.seedStock("SKU-1", 10);
    const existing = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const stockBefore = ReservationService.availableStock("SKU-1");
    const holdsBefore = ReservationService.holds().map((h) => h.holdId);

    expect(() =>
      ReservationService.expire("hold-does-not-exist"),
    ).toThrow(PreconditionError);

    expect(ReservationService.availableStock("SKU-1")).toBe(stockBefore);
    expect(ReservationService.holds().map((h) => h.holdId)).toEqual(
      holdsBefore,
    );
    expect(ReservationService.holds()[0]?.holdId).toBe(existing.holdId);
  });

  it("pre HoldPastTtl: hold not past TTL is rejected with named PreconditionError", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    // expiresAt remains in the future (ttlSeconds=300); no clock advance / sleep.

    let caught: unknown;
    try {
      ReservationService.expire(hold.holdId);
    } catch (e) {
      caught = e;
    }
    expect(caught).toBeInstanceOf(PreconditionError);
    expect(caught).not.toBeInstanceOf(UnauthorizedError);
    expect(caught).not.toBeInstanceOf(InsufficientStockError);
    expect(caught).not.toBeInstanceOf(TypeError);
    expect((caught as PreconditionError).errorType).toBe("PreconditionError");
    expect((caught as PreconditionError).name).toBe("PreconditionError");
  });

  it("post PreconditionErrorOnExpireHoldNotPastTtl: holds() equals holds()@pre when not past TTL", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const holdsBefore = ReservationService.holds().map((h) => ({ ...h }));

    expect(() => ReservationService.expire(hold.holdId)).toThrow(
      PreconditionError,
    );

    const holdsAfter = ReservationService.holds();
    expect(holdsAfter).toHaveLength(1);
    expect(holdsAfter[0]?.holdId).toBe(hold.holdId);
    expect(holdsAfter[0]?.sku).toBe(holdsBefore[0]?.sku);
    expect(holdsAfter[0]?.quantity).toBe(holdsBefore[0]?.quantity);
    expect(holdsAfter[0]?.expiresAt).toBe(holdsBefore[0]?.expiresAt);
  });

  it("post AvailableStockUnchangedOnExpireHoldNotPastTtl: availableStock equals @pre when not past TTL", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    const stockBefore = ReservationService.availableStock("SKU-1");
    expect(stockBefore).toBe(6);

    expect(() => ReservationService.expire(hold.holdId)).toThrow(
      PreconditionError,
    );

    expect(ReservationService.availableStock("SKU-1")).toBe(stockBefore);
    expect(ReservationService.availableStock("SKU-1")).toBe(6);
  });

  it("post AvailableStockRestoredOnExpiry: expire past TTL restores held quantity to available stock", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    const stockBefore = ReservationService.availableStock("SKU-1");
    expect(stockBefore).toBe(6);
    arrangeHoldPastTtl(hold);

    ReservationService.expire(hold.holdId);

    expect(ReservationService.availableStock("SKU-1")).toBe(
      stockBefore + hold.quantity,
    );
    expect(ReservationService.availableStock("SKU-1")).toBe(10);
  });

  it("post HoldRemoved: expire past TTL removes the hold", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    arrangeHoldPastTtl(hold);
    expect(ReservationService.holds()).toHaveLength(1);

    ReservationService.expire(hold.holdId);

    expect(ReservationService.holds()).toHaveLength(0);
    expect(
      ReservationService.holds().find((h) => h.holdId === hold.holdId),
    ).toBeUndefined();
  });

  it("post AvailableStockRestoredOnExpiry + HoldRemoved: other holds and their stock remain intact", () => {
    ReservationService.seedStock("SKU-1", 10);
    ReservationService.seedStock("SKU-2", 5);
    const hold1 = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const hold2 = ReservationService.reserve(AUTHORIZED, "SKU-2", 2, 300);
    expect(ReservationService.availableStock("SKU-1")).toBe(7);
    expect(ReservationService.availableStock("SKU-2")).toBe(3);
    arrangeHoldPastTtl(hold1);

    ReservationService.expire(hold1.holdId);

    expect(ReservationService.availableStock("SKU-1")).toBe(10);
    expect(ReservationService.availableStock("SKU-2")).toBe(3);
    expect(ReservationService.holds()).toHaveLength(1);
    expect(ReservationService.holds()[0]?.holdId).toBe(hold2.holdId);
  });
});

describe("OCL Reservation::lookup", () => {
  afterEach(() => {
    ReservationService.reset();
  });

  it("post ResultIsHoldDetails: authorized lookup returns that hold's sku, quantity, expiresAt, and current availableStock", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    const currentStock = ReservationService.availableStock("SKU-1");
    expect(currentStock).toBe(6);

    const result = ReservationService.lookup(AUTHORIZED, hold.holdId);

    expect(result.holdId).toBe(hold.holdId);
    expect(result.sku).toBe(hold.sku);
    expect(result.quantity).toBe(hold.quantity);
    expect(result.expiresAt).toBe(hold.expiresAt);
    expect(result.sku).toBe("SKU-1");
    expect(result.quantity).toBe(4);
    // OCL: result.availableStock = self.availableStock(hold.sku) now
    expect(result.availableStock).toBe(currentStock);
    expect(result.availableStock).toBe(
      ReservationService.availableStock(result.sku),
    );
    expect(result.availableStock).toBe(6);
  });

  it("post ResultIsHoldDetails: availableStock is current stock, not a reserve-time snapshot", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    expect(hold.availableStock).toBe(6);
    // Further reserve reduces current available stock after hold creation.
    ReservationService.reserve(AUTHORIZED, "SKU-1", 2, 300);
    const currentStock = ReservationService.availableStock("SKU-1");
    expect(currentStock).toBe(4);

    const result = ReservationService.lookup(AUTHORIZED, hold.holdId);

    expect(result.holdId).toBe(hold.holdId);
    expect(result.sku).toBe(hold.sku);
    expect(result.quantity).toBe(hold.quantity);
    expect(result.expiresAt).toBe(hold.expiresAt);
    expect(result.availableStock).toBe(currentStock);
    expect(result.availableStock).toBe(
      ReservationService.availableStock("SKU-1"),
    );
    expect(result.availableStock).toBe(4);
    expect(result.availableStock).not.toBe(hold.availableStock);
  });

  it("post AvailableStockUnchanged: authorized lookup leaves availableStock equal to @pre", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    const stockBefore = ReservationService.availableStock("SKU-1");
    expect(stockBefore).toBe(6);

    ReservationService.lookup(AUTHORIZED, hold.holdId);

    expect(ReservationService.availableStock("SKU-1")).toBe(stockBefore);
    expect(ReservationService.availableStock("SKU-1")).toBe(6);
  });

  it("post HoldsUnchanged: authorized lookup leaves holds() equal to holds()@pre", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    const holdsBefore = ReservationService.holds().map((h) => ({ ...h }));

    ReservationService.lookup(AUTHORIZED, hold.holdId);

    const holdsAfter = ReservationService.holds();
    expect(holdsAfter).toHaveLength(1);
    expect(holdsAfter[0]?.holdId).toBe(hold.holdId);
    expect(holdsAfter[0]?.sku).toBe(holdsBefore[0]?.sku);
    expect(holdsAfter[0]?.quantity).toBe(holdsBefore[0]?.quantity);
    expect(holdsAfter[0]?.expiresAt).toBe(holdsBefore[0]?.expiresAt);
  });

  it("post ResultIsHoldDetails + HoldsUnchanged + AvailableStockUnchanged: other holds and stock remain intact", () => {
    ReservationService.seedStock("SKU-1", 10);
    ReservationService.seedStock("SKU-2", 5);
    const hold1 = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const hold2 = ReservationService.reserve(AUTHORIZED, "SKU-2", 2, 300);
    const stock1Before = ReservationService.availableStock("SKU-1");
    const stock2Before = ReservationService.availableStock("SKU-2");
    const holdsBefore = ReservationService.holds().map((h) => h.holdId);
    expect(stock1Before).toBe(7);
    expect(stock2Before).toBe(3);

    const result = ReservationService.lookup(AUTHORIZED, hold1.holdId);

    expect(result.holdId).toBe(hold1.holdId);
    expect(result.sku).toBe(hold1.sku);
    expect(result.quantity).toBe(hold1.quantity);
    expect(result.expiresAt).toBe(hold1.expiresAt);
    expect(result.availableStock).toBe(stock1Before);
    expect(result.availableStock).toBe(
      ReservationService.availableStock(hold1.sku),
    );
    expect(result.availableStock).toBe(7);
    expect(ReservationService.availableStock("SKU-1")).toBe(stock1Before);
    expect(ReservationService.availableStock("SKU-2")).toBe(stock2Before);
    expect(ReservationService.holds().map((h) => h.holdId)).toEqual(
      holdsBefore,
    );
    expect(ReservationService.holds()).toHaveLength(2);
    expect(
      ReservationService.holds().find((h) => h.holdId === hold2.holdId),
    ).toBeDefined();
  });

  it("pre HoldExists / post HoldMissingOrNotVisibleErrorOnLookup: missing holdId yields named PreconditionError", () => {
    ReservationService.seedStock("SKU-1", 10);
    ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);

    let caught: unknown;
    try {
      ReservationService.lookup(AUTHORIZED, "hold-does-not-exist");
    } catch (e) {
      caught = e;
    }
    expect(caught).toBeInstanceOf(PreconditionError);
    expect(caught).not.toBeInstanceOf(UnauthorizedError);
    expect(caught).not.toBeInstanceOf(InsufficientStockError);
    expect(caught).not.toBeInstanceOf(TypeError);
    expect((caught as PreconditionError).errorType).toBe("PreconditionError");
    expect((caught as PreconditionError).name).toBe("PreconditionError");
  });

  it("post HoldsUnchangedOnHoldMissingLookup: holds() equals holds()@pre when hold missing", () => {
    ReservationService.seedStock("SKU-1", 10);
    const existing = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const stockBefore = ReservationService.availableStock("SKU-1");
    const holdsBefore = ReservationService.holds().map((h) => h.holdId);

    expect(() =>
      ReservationService.lookup(AUTHORIZED, "hold-does-not-exist"),
    ).toThrow(PreconditionError);

    expect(ReservationService.availableStock("SKU-1")).toBe(stockBefore);
    expect(ReservationService.holds().map((h) => h.holdId)).toEqual(
      holdsBefore,
    );
    expect(ReservationService.holds()[0]?.holdId).toBe(existing.holdId);
  });

  it("post HoldsUnchangedOnHoldMissingLookup: no hold mutation when none existed before missing lookup", () => {
    ReservationService.seedStock("SKU-1", 10);
    const stockBefore = ReservationService.availableStock("SKU-1");

    expect(() =>
      ReservationService.lookup(AUTHORIZED, "hold-does-not-exist"),
    ).toThrow(PreconditionError);

    expect(ReservationService.holds()).toHaveLength(0);
    expect(ReservationService.availableStock("SKU-1")).toBe(stockBefore);
  });

  it("pre PrincipalAuthorized: unauthorized principal is rejected", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);

    expect(() =>
      ReservationService.lookup(UNAUTHORIZED, hold.holdId),
    ).toThrow(UnauthorizedError);
  });

  it("post UnauthorizedErrorOnLookup: unauthorized yields named UnauthorizedError (not a language builtin)", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    let caught: unknown;
    try {
      ReservationService.lookup(UNAUTHORIZED, hold.holdId);
    } catch (e) {
      caught = e;
    }
    expect(caught).toBeInstanceOf(UnauthorizedError);
    expect(caught).not.toBeInstanceOf(PreconditionError);
    expect(caught).not.toBeInstanceOf(InsufficientStockError);
    expect(caught).not.toBeInstanceOf(TypeError);
    expect((caught as UnauthorizedError).errorType).toBe("UnauthorizedError");
    expect((caught as UnauthorizedError).name).toBe("UnauthorizedError");
  });

  it("post HoldsUnchangedOnUnauthorizedLookup: holds() equals holds()@pre when unauthorized", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const holdsBefore = ReservationService.holds().map((h) => ({ ...h }));

    expect(() =>
      ReservationService.lookup(UNAUTHORIZED, hold.holdId),
    ).toThrow(UnauthorizedError);

    const holdsAfter = ReservationService.holds();
    expect(holdsAfter).toHaveLength(1);
    expect(holdsAfter[0]?.holdId).toBe(hold.holdId);
    expect(holdsAfter[0]?.sku).toBe(holdsBefore[0]?.sku);
    expect(holdsAfter[0]?.quantity).toBe(holdsBefore[0]?.quantity);
    expect(holdsAfter[0]?.expiresAt).toBe(holdsBefore[0]?.expiresAt);
  });

  it("post AvailableStockUnchangedOnUnauthorizedLookup: availableStock for hold sku equals @pre when unauthorized", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const stockBefore = ReservationService.availableStock("SKU-1");
    expect(stockBefore).toBe(7);

    expect(() =>
      ReservationService.lookup(UNAUTHORIZED, hold.holdId),
    ).toThrow(UnauthorizedError);

    expect(ReservationService.availableStock("SKU-1")).toBe(stockBefore);
    expect(ReservationService.availableStock("SKU-1")).toBe(7);
  });
});

describe("OCL Reservation::list", () => {
  afterEach(() => {
    ReservationService.reset();
  });

  it("post EmptyCollectionWhenNoneVisible: authorized list returns empty array when no holds are visible", () => {
    ReservationService.seedStock("SKU-1", 10);

    const result = ReservationService.list(AUTHORIZED);

    expect(Array.isArray(result)).toBe(true);
    expect(result).toHaveLength(0);
    expect(result).toEqual([]);
  });

  it("post ResultIsFullDumpOfVisibleHolds: authorized list returns all visible holds as LookupResponse-equivalent items including availableStock", () => {
    ReservationService.seedStock("SKU-1", 10);
    ReservationService.seedStock("SKU-2", 5);
    const hold1 = ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    const hold2 = ReservationService.reserve(AUTHORIZED, "SKU-2", 2, 300);
    const stock1 = ReservationService.availableStock("SKU-1");
    const stock2 = ReservationService.availableStock("SKU-2");
    expect(stock1).toBe(6);
    expect(stock2).toBe(3);

    const result = ReservationService.list(AUTHORIZED);

    expect(Array.isArray(result)).toBe(true);
    expect(result).toHaveLength(2);
    const byId = new Map(result.map((r) => [r.holdId, r]));
    expect(byId.size).toBe(2);

    const item1 = byId.get(hold1.holdId);
    expect(item1).toBeDefined();
    expect(item1?.holdId).toBe(hold1.holdId);
    expect(item1?.sku).toBe(hold1.sku);
    expect(item1?.quantity).toBe(hold1.quantity);
    expect(item1?.expiresAt).toBe(hold1.expiresAt);
    expect(item1?.availableStock).toBe(stock1);
    expect(item1?.availableStock).toBe(
      ReservationService.availableStock(hold1.sku),
    );

    const item2 = byId.get(hold2.holdId);
    expect(item2).toBeDefined();
    expect(item2?.holdId).toBe(hold2.holdId);
    expect(item2?.sku).toBe(hold2.sku);
    expect(item2?.quantity).toBe(hold2.quantity);
    expect(item2?.expiresAt).toBe(hold2.expiresAt);
    expect(item2?.availableStock).toBe(stock2);
    expect(item2?.availableStock).toBe(
      ReservationService.availableStock(hold2.sku),
    );
  });

  it("post ResultIsFullDumpOfVisibleHolds: availableStock is current stock, not a reserve-time snapshot", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    expect(hold.availableStock).toBe(6);
    ReservationService.reserve(AUTHORIZED, "SKU-1", 2, 300);
    const currentStock = ReservationService.availableStock("SKU-1");
    expect(currentStock).toBe(4);

    const result = ReservationService.list(AUTHORIZED);

    const item = result.find((r) => r.holdId === hold.holdId);
    expect(item).toBeDefined();
    expect(item?.availableStock).toBe(currentStock);
    expect(item?.availableStock).toBe(
      ReservationService.availableStock("SKU-1"),
    );
    expect(item?.availableStock).not.toBe(hold.availableStock);
  });

  it("post ResultIsFullDumpOfVisibleHolds: list visibility matches get-by-id (same holds() universe)", () => {
    ReservationService.seedStock("SKU-1", 10);
    ReservationService.seedStock("SKU-2", 5);
    const hold1 = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const hold2 = ReservationService.reserve(AUTHORIZED, "SKU-2", 2, 300);

    const listed = ReservationService.list(AUTHORIZED);
    const listedIds = new Set(listed.map((r) => r.holdId));
    expect(listedIds).toEqual(new Set([hold1.holdId, hold2.holdId]));

    for (const hold of [hold1, hold2]) {
      const lookedUp = ReservationService.lookup(AUTHORIZED, hold.holdId);
      const listedItem = listed.find((r) => r.holdId === hold.holdId);
      expect(listedItem).toBeDefined();
      expect(listedItem?.sku).toBe(lookedUp.sku);
      expect(listedItem?.quantity).toBe(lookedUp.quantity);
      expect(listedItem?.expiresAt).toBe(lookedUp.expiresAt);
      expect(listedItem?.availableStock).toBe(lookedUp.availableStock);
    }
  });

  it("post HoldsUnchanged: authorized list leaves holds() equal to holds()@pre", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    const holdsBefore = ReservationService.holds().map((h) => ({ ...h }));

    ReservationService.list(AUTHORIZED);

    const holdsAfter = ReservationService.holds();
    expect(holdsAfter).toHaveLength(1);
    expect(holdsAfter[0]?.holdId).toBe(hold.holdId);
    expect(holdsAfter[0]?.sku).toBe(holdsBefore[0]?.sku);
    expect(holdsAfter[0]?.quantity).toBe(holdsBefore[0]?.quantity);
    expect(holdsAfter[0]?.expiresAt).toBe(holdsBefore[0]?.expiresAt);
  });

  it("post AvailableStockUnchanged: authorized list leaves availableStock equal to @pre", () => {
    ReservationService.seedStock("SKU-1", 10);
    ReservationService.seedStock("SKU-2", 5);
    ReservationService.reserve(AUTHORIZED, "SKU-1", 4, 300);
    ReservationService.reserve(AUTHORIZED, "SKU-2", 2, 300);
    const stock1Before = ReservationService.availableStock("SKU-1");
    const stock2Before = ReservationService.availableStock("SKU-2");
    expect(stock1Before).toBe(6);
    expect(stock2Before).toBe(3);

    ReservationService.list(AUTHORIZED);

    expect(ReservationService.availableStock("SKU-1")).toBe(stock1Before);
    expect(ReservationService.availableStock("SKU-2")).toBe(stock2Before);
  });

  it("post EmptyCollectionWhenNoneVisible + HoldsUnchanged + AvailableStockUnchanged: empty list does not mutate", () => {
    ReservationService.seedStock("SKU-1", 10);
    const stockBefore = ReservationService.availableStock("SKU-1");

    const result = ReservationService.list(AUTHORIZED);

    expect(result).toEqual([]);
    expect(ReservationService.holds()).toHaveLength(0);
    expect(ReservationService.availableStock("SKU-1")).toBe(stockBefore);
  });

  it("pre PrincipalAuthorized: unauthorized principal is rejected", () => {
    ReservationService.seedStock("SKU-1", 10);
    ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);

    expect(() => ReservationService.list(UNAUTHORIZED)).toThrow(
      UnauthorizedError,
    );
  });

  it("post UnauthorizedErrorOnList: unauthorized yields named UnauthorizedError (not a language builtin)", () => {
    ReservationService.seedStock("SKU-1", 10);
    ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    let caught: unknown;
    try {
      ReservationService.list(UNAUTHORIZED);
    } catch (e) {
      caught = e;
    }
    expect(caught).toBeInstanceOf(UnauthorizedError);
    expect(caught).not.toBeInstanceOf(PreconditionError);
    expect(caught).not.toBeInstanceOf(InsufficientStockError);
    expect(caught).not.toBeInstanceOf(TypeError);
    expect((caught as UnauthorizedError).errorType).toBe("UnauthorizedError");
    expect((caught as UnauthorizedError).name).toBe("UnauthorizedError");
  });

  it("post HoldsUnchangedOnUnauthorizedList: holds() equals holds()@pre when unauthorized", () => {
    ReservationService.seedStock("SKU-1", 10);
    const hold = ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const holdsBefore = ReservationService.holds().map((h) => ({ ...h }));

    expect(() => ReservationService.list(UNAUTHORIZED)).toThrow(
      UnauthorizedError,
    );

    const holdsAfter = ReservationService.holds();
    expect(holdsAfter).toHaveLength(1);
    expect(holdsAfter[0]?.holdId).toBe(hold.holdId);
    expect(holdsAfter[0]?.sku).toBe(holdsBefore[0]?.sku);
    expect(holdsAfter[0]?.quantity).toBe(holdsBefore[0]?.quantity);
    expect(holdsAfter[0]?.expiresAt).toBe(holdsBefore[0]?.expiresAt);
  });

  it("post AvailableStockUnchangedOnUnauthorizedList: availableStock equals @pre when unauthorized", () => {
    ReservationService.seedStock("SKU-1", 10);
    ReservationService.reserve(AUTHORIZED, "SKU-1", 3, 300);
    const stockBefore = ReservationService.availableStock("SKU-1");
    expect(stockBefore).toBe(7);

    expect(() => ReservationService.list(UNAUTHORIZED)).toThrow(
      UnauthorizedError,
    );

    expect(ReservationService.availableStock("SKU-1")).toBe(stockBefore);
    expect(ReservationService.availableStock("SKU-1")).toBe(7);
  });

  it("post HoldsUnchangedOnUnauthorizedList + AvailableStockUnchangedOnUnauthorizedList: no mutation when none existed before unauthorized list", () => {
    ReservationService.seedStock("SKU-1", 10);
    const stockBefore = ReservationService.availableStock("SKU-1");

    expect(() => ReservationService.list(UNAUTHORIZED)).toThrow(
      UnauthorizedError,
    );

    expect(ReservationService.holds()).toHaveLength(0);
    expect(ReservationService.availableStock("SKU-1")).toBe(stockBefore);
  });
});
