# frozen_string_literal: true

# Contract specs derived from contracts/Calculator.ocl
# (regenerated by solidsdd.derive.tests → ruby-rspec adapter).

RSpec.describe Calculator do
  describe ".add" do
    it "post ResultIsSum: result = a + b" do
      expect(Calculator.add(2, 3)).to eq(5)
      expect(Calculator.add(-1, 1)).to eq(0)
    end
  end

  describe ".sub" do
    it "post ResultIsDifference: result = a - b" do
      expect(Calculator.sub(5, 3)).to eq(2)
      expect(Calculator.sub(-1, 1)).to eq(-2)
    end
  end

  describe ".mul" do
    it "post ResultIsProduct: result = a * b" do
      expect(Calculator.mul(4, 3)).to eq(12)
      expect(Calculator.mul(-2, 3)).to eq(-6)
    end
  end

  describe ".div" do
    it "pre DivisorIsNonZero: b <> 0 is enforced" do
      expect { Calculator.div(1, 0) }.to raise_error(Calculator::PreconditionError)
    end

    it "post ResultIsQuotient: result = a / b" do
      expect(Calculator.div(6, 3)).to eq(2.0)
      expect(Calculator.div(-6, 3)).to eq(-2.0)
    end
  end

  describe ".mod" do
    it "pre DivisorIsNonZero: b <> 0 is enforced" do
      expect { Calculator.mod(1, 0) }.to raise_error(Calculator::PreconditionError)
    end

    it "post ResultIsRemainder: result = a % b" do
      expect(Calculator.mod(7, 3)).to eq(7 % 3)
      expect(Calculator.mod(-7, 3)).to eq((-7) % 3)
      expect(Calculator.mod(7, -3)).to eq(7 % -3)
      expect(Calculator.mod(-7, -3)).to eq((-7) % -3)
    end
  end
end
