/**
 * Contract tests derived from contracts/Calculator.ocl
 * (regenerated by solidsdd.derive.tests).
 */
import { describe, expect, it } from "vitest";
import { Calculator, PreconditionError } from "../../src/calculator.js";

describe("OCL Calculator::add", () => {
  it("post ResultIsSum: result = a + b", () => {
    expect(Calculator.add(2, 3)).toBe(5);
    expect(Calculator.add(-1, 1)).toBe(0);
  });
});

describe("OCL Calculator::sub", () => {
  it("post ResultIsDifference: result = a - b", () => {
    expect(Calculator.sub(5, 3)).toBe(2);
    expect(Calculator.sub(-1, 1)).toBe(-2);
  });
});

describe("OCL Calculator::mul", () => {
  it("post ResultIsProduct: result = a * b", () => {
    expect(Calculator.mul(4, 3)).toBe(12);
    expect(Calculator.mul(-2, 3)).toBe(-6);
  });
});

describe("OCL Calculator::div", () => {
  it("pre DivisorIsNonZero: b <> 0 is enforced", () => {
    expect(() => Calculator.div(1, 0)).toThrow(PreconditionError);
  });

  it("post ResultIsQuotient: result = a / b", () => {
    expect(Calculator.div(6, 3)).toBe(2);
    expect(Calculator.div(-6, 3)).toBe(-2);
  });
});

describe("OCL Calculator::mod", () => {
  it("pre DivisorIsNonZero: b <> 0 is enforced", () => {
    expect(() => Calculator.mod(1, 0)).toThrow(PreconditionError);
  });

  // OCL: result = a - b * (a / b).truncatedTowardZero() ≡ JavaScript a % b
  it("post ResultIsRemainder: result = a % b", () => {
    expect(Calculator.mod(7, 3)).toBe(7 % 3);
    expect(Calculator.mod(-7, 3)).toBe((-7) % 3);
    expect(Calculator.mod(7, -3)).toBe(7 % -3);
    expect(Calculator.mod(-7, -3)).toBe((-7) % -3);
  });
});

describe("OCL Calculator::pow", () => {
  it("post ResultIsPower: result = a ** b", () => {
    expect(Calculator.pow(2, 3)).toBe(2 ** 3);
    expect(Calculator.pow(-2, 3)).toBe((-2) ** 3);
    expect(Calculator.pow(5, 0)).toBe(5 ** 0);
  });

  // No `pre` clause in OCL (deliberate — ChangeBrief X4): pow must never
  // reject inputs that div/mod would reject as zero-divisor violations.
  it("has no precondition: never rejects b <= 0 or a == 0 with PreconditionError", () => {
    expect(() => Calculator.pow(2, 0)).not.toThrow(PreconditionError);
    expect(() => Calculator.pow(2, -1)).not.toThrow(PreconditionError);
    expect(() => Calculator.pow(0, 0)).not.toThrow(PreconditionError);
    expect(Calculator.pow(2, 0)).toBe(1);
    expect(Calculator.pow(2, -1)).toBe(0.5);
  });
});

describe("OCL Calculator::avg", () => {
  it("post ResultIsMean: result = (a + b) / 2", () => {
    expect(Calculator.avg(2, 4)).toBe((2 + 4) / 2);
    expect(Calculator.avg(-2, 3)).toBe((-2 + 3) / 2);
    expect(Calculator.avg(0, 0)).toBe(0);
  });

  // No `pre` clause in OCL (deliberate — ChangeBrief X4): avg must never
  // reject inputs that div/mod would reject as zero-divisor violations.
  it("has no precondition: never rejects b <= 0 or a == 0 with PreconditionError", () => {
    expect(() => Calculator.avg(2, 0)).not.toThrow(PreconditionError);
    expect(() => Calculator.avg(0, -1)).not.toThrow(PreconditionError);
    expect(() => Calculator.avg(0, 0)).not.toThrow(PreconditionError);
    expect(Calculator.avg(2, 0)).toBe(1);
    expect(Calculator.avg(0, -1)).toBe(-0.5);
  });
});
