/**
 * Contract tests derived from contracts/Memory.ocl
 * (regenerated by solidsdd.derive.tests).
 */
import { describe, expect, it } from "vitest";
import { Memory } from "../../src/memory.js";

describe("OCL Memory initial state", () => {
  it("initial memory is 0 (fresh instance)", () => {
    const m = new Memory();
    expect(m.recall()).toBe(0);
  });

  it("initial memory is 0 after clear", () => {
    const m = new Memory();
    m.add(10);
    m.clear();
    expect(m.recall()).toBe(0);
  });
});

describe("OCL Memory::clear", () => {
  it("post MemoryCleared: memory = 0; ResultIsZero: result = 0", () => {
    const m = new Memory();
    m.add(5);
    expect(m.clear()).toBe(0);
    expect(m.recall()).toBe(0);
  });
});

describe("OCL Memory::recall", () => {
  it("post ResultIsMemory: result = memory", () => {
    const m = new Memory();
    expect(m.recall()).toBe(0);
    m.add(7);
    expect(m.recall()).toBe(7);
    m.subtract(2);
    expect(m.recall()).toBe(5);
  });
});

describe("OCL Memory::add", () => {
  it("post MemoryIncreased: memory = memory@pre + value; ResultIsMemory: result = memory", () => {
    const m = new Memory();
    expect(m.add(3)).toBe(3);
    expect(m.recall()).toBe(3);
    expect(m.add(4)).toBe(7);
    expect(m.recall()).toBe(7);
    expect(m.add(-2)).toBe(5);
    expect(m.recall()).toBe(5);
  });
});

describe("OCL Memory::subtract", () => {
  it("post MemoryDecreased: memory = memory@pre - value; ResultIsMemory: result = memory", () => {
    const m = new Memory();
    m.add(10);
    expect(m.subtract(3)).toBe(7);
    expect(m.recall()).toBe(7);
    expect(m.subtract(2)).toBe(5);
    expect(m.recall()).toBe(5);
    expect(m.subtract(-1)).toBe(6);
    expect(m.recall()).toBe(6);
  });
});
